[package]
name = "capnpoc"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
capnp = "0.21.1"
yoke = { version = "0.8.0", features = ["derive"] }

[profile.profiling]
inherits = "release"
debug = true
